### PR TITLE
Added thunderwave.bit domain support

### PR DESCRIPTION
**Pull request by Plasmmer**

### CODE REVIEW

**Comment by AnthyG** [comment]
Well, this is a real bummer, as you probably paid something, but the domain should at least be "thunder*wave*.bit", shouldn't it?

Wow. I feel really evil 😢

**Comment by Plasmmer** [comment]
> but the domain should at least be "thunderwave.bit", shouldn't it?

This is the domain. "thunderbolt.bit" was typing error in the commit, you can see the real domain in the content.json.

**Comment by AnthyG** [comment]
```
 + "domain": "thunderbolt.bit",
```
It clearly says "thunderbolt" :|

**Comment by Plasmmer** [comment]
Fixed.

**Comment by AnthyG** [comment]
May I ask, how much a `.bit`-Domain costs for you?
([zero/thunderwave.bit](http://127.0.0.1:43110/thunderwave.bit/) isn't yet available)

**Comment by Plasmmer** [comment]
I'd registered thunderbolt instead of thunderwave. Now I'm registering thunderwave.bit

**Comment by AnthyG** [comment]
Many thanks!
It is very nice of you, that you provide a domain-name for ThunderWave 😃👍

**Comment by Plasmmer** [comment]
Working: https://bit.surf:43110/thunderwave.bit

**Pull request merged**
